Feature/black
uktrade/trade-remedies-api pull request #12
Opened 2020-10-28 14:11 UTC by Luisella21

Applied  black to the code base, run flake8 and fixed the relevant errors. Changed circleci configuration to run black and flake8.

2020-10-29 09:32 UTC, rossmiller requested changes
Very nice! Some comments to address.

2020-10-29 09:32 UTC, rossmiller commented on trade_remedies_api/audit/utils.py
> +        key = ""  # TODO this is added to stop error 'undefined name' Check what is the right fix
Do we know the answer to this?

2020-10-29 09:32 UTC, rossmiller commented on trade_remedies_api/cases/services/api.py
> +        case_type_id = request.data.get("case_type_id")
Why has this been uncommented?

2020-10-29 09:32 UTC, rossmiller commented on trade_remedies_api/cases/services/api.py
> +            case.modify_case_type(case_type_id, requested_by=request.user)
Why has this been changed?

2020-10-29 09:32 UTC, rossmiller commented on trade_remedies_api/cases/services/urls.py
> +    ),  # noqa: E501
This appears to be a mistake.

2020-10-29 09:32 UTC, rossmiller commented on trade_remedies_api/contacts/services/api.py
> -                ccs = CaseContact.objects.get_or_create(
Presumably this variable was not used?

2020-10-29 09:32 UTC, rossmiller commented on trade_remedies_api/contacts/services/api.py
> -        result = CaseContact.objects.filter(contact=contact).delete()
Presumably this variable was not used?

2020-10-29 09:32 UTC, rossmiller commented on trade_remedies_api/core/management/commands/load_sysparams.py
> +logger = logging.getLogger(__name__)
This looks like a mistake.

2020-10-29 09:32 UTC, rossmiller commented on trade_remedies_api/core/services/auth.py
> +                        "error": "You have entered an incorrect code too many times and "
Does that structure function as expected?

2020-10-29 09:32 UTC, rossmiller commented on trade_remedies_api/organisations/services/api.py
> -                if not contact_id in contacts:
Does the replacement have the same logical effect?

2020-10-29 09:32 UTC, rossmiller commented on trade_remedies_api/workflow/services/api.py
> +        # TODO flake8 fix F821 undefined name 'item'
Is this TODO still required?

2020-10-29 09:32 UTC, rossmiller commented on trade_remedies_api/workflow/models.py
> +            # TODO fix F821 (undefined name 'state') instead of using noqa
Is this TODO still required?

2020-10-29 09:42 UTC, Luisella21 commented on trade_remedies_api/cases/services/api.py
> +            case.modify_case_type(case_type_id, requested_by=request.user)
modified was not used and was giving the flake8 errorF841 (local variable  assigned to but never used)

2020-10-29 09:56 UTC, Luisella21 commented on trade_remedies_api/audit/utils.py
> +        key = ""  # TODO this is added to stop error 'undefined name' Check what is the right fix
I checked the code in more details, and the key is initialised correctly.

2020-10-29 09:57 UTC, Luisella21 commented on trade_remedies_api/cases/services/api.py
> +        case_type_id = request.data.get("case_type_id")
Mistake!

2020-10-29 09:58 UTC, Luisella21 commented on trade_remedies_api/cases/services/urls.py
> +    ),  # noqa: E501
Fixed!

2020-10-29 09:58 UTC, Luisella21 commented on trade_remedies_api/contacts/services/api.py
> -                ccs = CaseContact.objects.get_or_create(
Exactly.

2020-10-29 10:01 UTC, Luisella21 commented on trade_remedies_api/core/services/auth.py
> +                        "error": "You have entered an incorrect code too many times and "
I restored the long line.

2020-10-29 10:04 UTC, Luisella21 commented on trade_remedies_api/workflow/services/api.py
> +        # TODO flake8 fix F821 undefined name 'item'
No! Removed it.

2020-10-29 10:05 UTC, Luisella21 commented on trade_remedies_api/workflow/models.py
> +            # TODO fix F821 (undefined name 'state') instead of using noqa
No, removed it.

2020-10-29 11:43 UTC, Luisella21 commented on trade_remedies_api/contacts/services/api.py
> -        result = CaseContact.objects.filter(contact=contact).delete()
Correct.

2020-10-29 11:45 UTC, Luisella21 commented on trade_remedies_api/organisations/services/api.py
> -                if not contact_id in contacts:
Yes, it does.

2020-10-29 11:55 UTC, Luisella21 commented on trade_remedies_api/core/management/commands/load_sysparams.py
> +logger = logging.getLogger(__name__)
It was giving the error 'import but not used'
I reinstated it, and used noqa to stop the flake8 error.

2020-11-09 13:45 UTC, rossmiller approved these changes
LGTM!

2020-11-24 12:11 UTC, merged