TRSV2-144: allow email to be sent with edited deadline
uktrade/trade-remedies-api pull request #165
Opened 2022-03-25 09:45 UTC by KnowYourLines

2022-03-25 13:11 UTC, nboyse requested changes
All good, small change to gitignore

2022-03-25 13:11 UTC, nboyse commented on .gitignore
> +fitness/fitness_metrics_graph.png
Should be excluded from PR, not in gitignore

2022-03-25 13:16 UTC, KnowYourLines commented on .gitignore
> +fitness/fitness_metrics_graph.png
Don't believe it's actually possible to selectively exclude files from a PR. This is a temporary fix to prevent merge conflicts from occurring when fitness function stuff is updated automatically. @chris-pettinga is working on a more long-term fix.

2022-03-25 13:17 UTC, KnowYourLines commented on .gitignore
> +fitness/fitness_metrics_graph.png
Actually, might just give https://stackoverflow.com/questions/20120478/ignoring-specific-files-file-types-or-folders-in-a-pull-request-diff a go

2022-03-25 13:30 UTC, KnowYourLines commented on .gitignore
> +fitness/fitness_metrics_graph.png
But why would we want to track fitness function output in version control? Can't see the point, and doing anything more on this probably beyond the scope of this ticket.

2022-03-25 13:37 UTC, KnowYourLines commented on .gitignore
> +fitness/fitness_metrics_graph.png
merge develop into branch and resolve the conflicts manually until it's sorted, i.e. accept develop's fitness database since it seems they need to be in VCS

2022-03-28 08:36 UTC, chris-pettinga approved these changes

2022-03-28 08:39 UTC, nboyse approved these changes

2022-03-28 08:40 UTC, merged