V2 Feature - TRSV2-206 - V2 registration journey unhappy path
uktrade/trade-remedies-api pull request #219
Opened 2022-05-25 15:55 UTC by chris-pettinga

2022-06-09 12:01 UTC, KnowYourLines requested changes

2022-06-09 12:01 UTC, KnowYourLines commented on trade_remedies_api/core/services/urls.py
> +    path("validation_error/<str:key>/", ValidationErrorAPIView.as_view()),
Same as above.

2022-06-09 12:26 UTC, KnowYourLines commented on trade_remedies_api/config/urls.py
>      ),
These were introduced with login v2, right? It may be too late to rename them for now, but still useful to cover them with functional tests.

2022-06-14 14:56 UTC, chris-pettinga commented on trade_remedies_api/config/urls.py
> +    ),
Good point, I've added functional tests for the Registration, Email Verify, and 2FA views

2022-06-22 09:05 UTC, KnowYourLines commented
Can we move `trade_remedies_api/core/services/auth/tests/test_functional.py` and `trade_remedies_api/core/services/auth/tests/test_functional.py` into `trade_remedies_api/functional_tests/test_2fa.py` and `trade_remedies_api/functional_tests/test_registration.py`? To me at least, it makes more sense to separate tests of our functionality from where the implementation of our functionality lives.

Otherwise looks good, but needs tests and CI passing. Looks like the test for 2fa is failing because of a missing header in the request. And other tests are failing because the django management command isn't being run from a place where it can find the path to the system parameter json file. You may need to either change the location the tests are located and run from or modify the django management command to accept a path and use a default path if one is not provided to get the tests passing.

2022-06-22 09:52 UTC, KnowYourLines approved these changes
LGTM but precommit hooks don't agree

2022-06-22 09:52 UTC, merged