TRSv2-293 - Caseworker invite public join case
uktrade/trade-remedies-api pull request #282
Opened 2022-10-21 08:47 UTC by nahmed99

2022-10-25 15:24 UTC, chris-pettinga requested changes

2022-10-25 15:24 UTC, chris-pettinga commented on trade_remedies_api/organisations/services/v2/serializers.py
> +        return [ContactSerializer(each).data for each in instance.contacts.all()]
```suggestion
        return ContactSerializer(instance.contacts.all(), many=True).data
```

2022-11-09 13:31 UTC, nahmed99 commented on trade_remedies_api/organisations/services/v2/serializers.py
> +        return [ContactSerializer(each).data for each in instance.contacts.all()]
Done.

2022-11-09 15:53 UTC, chris-pettinga requested changes

2022-11-09 15:53 UTC, chris-pettinga commented on trade_remedies_api/invitations/services/v2/views.py
> +                login_url = public_login_url()
is this function called anywhere else? If not, best to leave the return value here so future readers dont have to go to lots of different places to find out what a function is doing.

2022-11-09 15:53 UTC, chris-pettinga commented on trade_remedies_api/organisations/services/v2/views.py
> +            .filter(similarity__gt=0.3)
sidenote, but did you play around with this value to make it as user-friendly as possible. I think a higher value would yield less results (as it would demand the company name be very similar to the string being searched) but it is worth the exercise I think.

2022-11-09 16:03 UTC, nahmed99 commented on trade_remedies_api/invitations/services/v2/views.py
> +                login_url = public_login_url()
Yes (public_login_url()) used in multiple places.

2022-11-10 10:46 UTC, nahmed99 commented on trade_remedies_api/organisations/services/v2/views.py
> +            .filter(similarity__gt=0.3)
Done - using 0.1 for better results.

2022-11-14 09:43 UTC, chris-pettinga approved these changes
LGTM

2022-12-21 16:20 UTC, closed without merging