Release 2.1.7
uktrade/trade-remedies-api pull request #303
Opened 2022-12-08 17:04 UTC by chris-pettinga

2022-12-09 16:50 UTC, osimuka requested changes

2022-12-09 16:50 UTC, osimuka commented on trade_remedies_api/invitations/services/v2/tests/test_views.py
> +    """def test_user_cases_to_link_deleted(self):
Why is this test commented out?
Should we remove it all together?

2022-12-12 09:39 UTC, chris-pettinga commented on trade_remedies_api/invitations/services/v2/tests/test_views.py
> +    """def test_user_cases_to_link_deleted(self):
good spot, have removed it.

2022-12-12 10:02 UTC, osimuka approved these changes

2022-12-13 19:52 UTC, merged