Support for BDD testing of login.
uktrade/trade-remedies-api pull request #34
Opened 2020-12-23 15:39 UTC by Luisella21

2020-12-24 12:36 UTC, davecharles requested changes
Great start but wondering if we can take a more rest-y approach

2020-12-24 12:36 UTC, davecharles commented on trade_remedies_api/api_test/urls.py
> +        "api-test-obj/create-test-user/<str:email>/<str:password>/<str:group>/", create_test_user,
Probably requires a longer discussion but basically think that even though these are test fixtures we should still take a solid API design approach - this will be beneficial for extensibility, maintainability etc. A lot of resources on this, [this one is ok](https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/). Given the notion `Use nouns instead of verbs in endpoint paths` the path should be something like:
```python
from api_test.views import user, 
...
path("api-test-obj/users/", users),  # post or delete on the users collection
path("api-test-obj/users/<str:name>", user),  # given username, update a user 
...
```
and the test client that needs the fixture will perform a `POST` to create the resource (or DELETE or PATCH etc), so in `api_test/views.py` something like:
```python
@api_view(http_method_names=['POST', 'DELETE'])
...
def users(request):
    username = request.data.get("name")
    if request.method == 'POST':
        user = User.objects.create_user(
            name=username,
            email=request.data.get("email")
            ...
        )
        return Response(status=201, {"message": f"user {username} created"})
    else:  # DELETE
        User.objects.get(name=request.data.get("name")).delete(True)
        return Response(status=204)  # assuming all ok

@api_view(http_method_names=['PATCH'])
...
def user(request):
    user =  User.objects.get(name=request.data.get("name"))
    # Update the user from request data
    ...
    return Response(status=202, {"message": f"user {username} updated"})  # assuming all ok
```
I can envisage test scenarios where update/delete (PATCH/DELETE) of a fixture might be useful. Pretty sure we don't need GET. We might want to discuss what we should return (e.g. should we return a json representation of the created/updated object?).

2020-12-24 12:36 UTC, davecharles commented on trade_remedies_api/api_test/views.py
> +def create_test_user(request, email, password, group):
See comment on `urls.py`

2020-12-29 13:35 UTC, Luisella21 commented on docker-compose-bdd.yml
> +version: "3"
Removed.

2021-01-06 16:19 UTC, davecharles approved these changes
LGTM

2021-01-06 17:24 UTC, merged