fixi for bug api v1 graceful no case
uktrade/trade-remedies-api pull request #354
Opened 2023-02-28 18:04 UTC by osimuka

2023-03-06 09:54 UTC, chris-pettinga requested changes

2023-03-06 09:54 UTC, chris-pettinga commented on trade_remedies_api/cases/services/api.py
> +            if queryset:
I think replace this with a try except Case.DoesNotExist

It is easier to read and still allows us to catch exceptions where multiple case objects are returned (something which we would need to know about)

2023-03-06 15:52 UTC, nahmed99 commented on pii-ner-exclude.txt
> +XML
I think one entry might be sufficient for the pii pre-commit. Same comment a bit further below.

2023-03-07 09:27 UTC, osimuka commented on trade_remedies_api/cases/services/api.py
> +            case = get_object_or_404(
@chris-pettinga the return and the log statement below is for when the match is not existent, that will not raise a 404

2023-03-07 09:40 UTC, nahmed99 approved these changes

2023-03-07 11:31 UTC, yusufsheiqh commented on trade_remedies_api/cases/services/api.py
> +            case = get_object_or_404(
I'm not sure I understand what's happening here. How would we get a match but also a 404?

2023-03-07 11:37 UTC, chris-pettinga commented on trade_remedies_api/cases/services/api.py
> +            case = get_object_or_404(
@yusufsheiqh I think I see, a match means that something that looks like (regex) a case number was in the case_number variable, but the 404 means that the case couldn't be found, e.g. with case reference TD000

2023-03-07 11:38 UTC, chris-pettinga approved these changes

2023-03-07 11:45 UTC, yusufsheiqh commented on trade_remedies_api/cases/services/api.py
> +            case = get_object_or_404(
I see. Should we be logging when this happens when there's a match but there is no case as well then? From my understanding, this will only return Http404.

2023-03-07 11:46 UTC, chris-pettinga commented on trade_remedies_api/cases/services/api.py
> +            case = get_object_or_404(
Yes fair enough

2023-03-07 12:12 UTC, osimuka commented on trade_remedies_api/cases/services/api.py
> +            case = get_object_or_404(
@chris-pettinga and @yusufsheiqh 
Using the method `get_object_or_404` will have jumped out of the function already before loggin can happen, unless we use a `try` and `except` to hand the raise ourselves then we can add the log before raising .

However this is v1 code that will be replaced soon, so sentry can be just enough for now.

Let me know your thoughts

2023-03-07 12:49 UTC, yusufsheiqh approved these changes

2023-03-07 13:15 UTC, merged