wip
uktrade/trade-remedies-api pull request #371
Opened 2023-03-28 18:26 UTC by osimuka

2023-03-29 09:55 UTC, yusufsheiqh reviewed
I assume some tests will follow, so I will be happy to review this again for approval.

2023-03-29 09:55 UTC, yusufsheiqh commented on trade_remedies_api/config/serializers.py
> +    should be a read-only operation, we will use this read-only serializer
```suggestion
    A read-only serializer for models.
    In a writable ModelSerializer a lot of time is spent on validations
    So to speed up the operation where we are getting a list of objects which
    should be a read-only operation, we will use this read-only serializer.
```

2023-03-29 11:33 UTC, osimuka commented on trade_remedies_api/config/serializers.py
> +class GenericSerializerType(typing.Protocol):
Yah, its an interesting topic, `Protocols` are relatively new in python, very useful for type annotation when you are writing modules which reference example an api which implementation of a giving method is unknown, example implementing api binds to drivers

2023-03-29 15:07 UTC, yusufsheiqh approved these changes

2023-03-31 08:35 UTC, chris-pettinga requested changes

2023-03-31 08:35 UTC, chris-pettinga commented on trade_remedies_api/config/viewsets.py
> +        if model_name == "Organisation":
I think we need to make this more dynamic rather than having a bunch of if statements. Perhaps something (similar to the above method) that creates a BaseSerialzier class from the normal serializer that only contains either:

fields that the model has itself
methods that override the drf base serializer class

2023-04-05 12:27 UTC, nahmed99 approved these changes

2023-04-05 13:37 UTC, chris-pettinga approved these changes

2023-04-05 13:42 UTC, merged