Reorganise repo to being into line with LST canonical structure
uktrade/trade-remedies-api pull request #8
Opened 2020-09-30 12:30 UTC by rossmiller

This amends the folder structure, config and approach to Django setup and docker to bring the project into line with other Live Services projects.

2020-10-14 12:46 UTC, jwgulley commented on Makefile
> -SHELL := /bin/bash
Are we still able to run the code quality checks locally?

2020-10-14 12:48 UTC, jwgulley commented on README.md
> +Firstly, you should copy local.env.example to local.env and add the necessary environment variables for a local development environment.  local.env is in .gitignore and should not be committed to the
How will people know how to modify local.env?

2020-10-14 12:55 UTC, jwgulley commented on README.md
> +If you are not sure what to use for one of the values above, ask a colleague or contact the SRE team.
There is clearly scope to make this more repeatable.  Whether it is worth it depends on how many people will go through the process.  A possible step forward would be to put a sample file in a Jira page or similar and refer to it here.

2020-10-14 12:58 UTC, jwgulley commented on docker-compose.yml
> +version: "3"
I noted that the config.yml version changes from 2 to 2.1.  Here it changes from 2 to 3.  Is consistency needed?

2020-10-14 13:04 UTC, jwgulley commented on requirements/base.txt
> +# This file is autogenerated by pip-compile
If the file is autogenerated by pip-compile, perhaps consider removing it from source control ?

2020-10-14 13:04 UTC, jwgulley commented on requirements/dev.txt
> +# This file is autogenerated by pip-compile
See above comment.

2020-10-14 13:05 UTC, jwgulley commented on requirements/prod.txt
> +# This file is autogenerated by pip-compile
See above comment.

2020-10-14 13:10 UTC, jwgulley commented on trade_remedies_api/audit/tasks.py
> +    logger.debug(f"Total pending audits: {len(audits)}")
Why did you decide to make some logging statements "debug" and others "info"?

2020-10-14 13:12 UTC, jwgulley commented on trade_remedies_api/cases/management/commands/reset_case_data.py
> +        logger.info("Completed reset_case_data command")
Always good to see log statements which are CLEAR :-)

2020-10-14 13:16 UTC, jwgulley commented on trade_remedies_api/cases/tasks.py
> +            # print( TODO - remove if not needed
If in doubt, log it!?!

2020-10-14 13:17 UTC, jwgulley commented on trade_remedies_api/cases/tests/test_case.py
> +    path = "core/system/parameters.json"
Are there any possible disadvantages to removing the reference to settings.SITE_ROOT?

2020-10-14 13:22 UTC, jwgulley commented on trade_remedies_api/core/base.py
> -                #    print(f'Field not found "{field}"')
Not worth a log message?

2020-10-14 13:24 UTC, jwgulley commented on trade_remedies_api/core/management/commands/load_sysparams.py
> +            default="core/system/parameters.json",
See similar comment above.

2020-10-14 13:30 UTC, jwgulley commented on trade_remedies_api/core/tasks.py
> +
Is this a fix to an issue with email being sent?  Presumably this issue does not arise in production?

2020-10-14 13:32 UTC, jwgulley commented on trade_remedies_api/documents/tasks.py
> +    logger.info(result)
Does the result need a string to say what it is?

2020-10-14 14:19 UTC, jwgulley commented on trade_remedies_api/workflow/models.py
> +            logger.debug(f"NO outcome spec: {node.get('outcome_spec')}")
Why debug?  If this is a non standard execution path, do we not to know it happened?

2020-10-14 14:23 UTC, jwgulley reviewed
Bravo, Ross.  Looks good to me and I have been using the result successfully for development.  Obviously, I don't understand all the details, but I hope some of the comments below are helpful.  If not, please just close the comment down.

2020-10-15 07:33 UTC, markhigham requested changes
The api container fails to start locally or on circleci
django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable

2020-10-26 18:56 UTC, markhigham approved these changes

2020-10-28 12:28 UTC, merged